services:
  - type: web
    name: webapp-fashion-static
    runtime: static
    plan: free
    rootDir: frontend
    autoDeployTrigger: commit
    buildCommand: npm install --no-audit --no-fund && CI=false npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_MAPS_ENABLED
        value: "false"